[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/license"
  to = "/license.html"
  status = 200

[[redirects]]
  from = "/ledger"
  to = "/ledger.html"
  status = 200

[[redirects]]
  from = "/seals"
  to = "/seals.html"
  status = 200

[[redirects]]
  from = "/glyphs"
  to = "/glyphs.html"
  status = 200

[[redirects]]
  from = "/stars"
  to = "/stars.html"
  status = 200

[[redirects]]
  from = "/universal"
  to = "/universal.html"
  status = 200
