apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-api
  namespace: codex-aeturnum
  labels:
    app: codex-aeturnum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codex-api
  template:
    metadata:
      labels:
        app: codex-api
      annotations:
        codex.aeturnum/subject_sha256: "0f9d6b0c0e9f07e6a4cd3f8cc7e5c8a8f1e3b3f6f4b5a6c7d8e9f0a1b2c3d4e5"
    spec:
      containers:
      - name: codex-api
        # Replace image with your built image or GHCR path
        image: ghcr.io/calebfbyker-lab/domionnexus:codex-api-latest
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /livez
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: codex-api
  namespace: codex-aeturnum
spec:
  selector:
    app: codex-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
