[project]
name = "codex-neuro"
version = "103.0.0"
description = "Codex Aeturnum neurocybernetics (signals, decoder, sim)"
requires-python = ">=3.11"
dependencies = ["numpy>=1.26.4","scipy>=1.13.1"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
