[project]
name = "codex-core"
version = "103.0.0"
description = "Codex Aeturnum core (tetra-helix, chrono-merkle, holonous)"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
