name: api-ci
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          cd services/api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python - <<'PY'
print('API build OK')
PY
