image:
  repository: ghcr.io/${GITHUB_OWNER}/codex-v90x
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  - name: CODEX_API_KEY
    valueFrom:
      secretKeyRef:
        name: codex-secrets
        key: CODEX_API_KEY
