global:
  scrape_interval: ${PROM_SCRAPE}
scrape_configs:
  - job_name: 'nexus'
    static_configs:
      - targets: ['nexus:8020']
    metrics_path: /metrics
    scheme: http
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:8010']
    metrics_path: /metrics
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']
    metrics_path: /metrics
