name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run CI-like build
        run: |
          python3 scripts/determinism_env.py
          python3 scripts/hash_all.py
          python3 scripts/verify_manifest.py
          python3 scripts/sbom_syft_stub.py
          python3 scripts/vuln_gate.py
          python3 scripts/provenance_v4.py
          python3 scripts/dsse_hmac_sign.py
