name: v96-ci
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ main, master ] }
jobs:
  verify-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python scripts/hash_all.py --root . --out codex/manifest.v96.json
          python scripts/verify_manifest.py --root . --manifest codex/manifest.v96.json
          python scripts/sbom_syft_stub.py
          python scripts/vuln_gate.py --sbom sbom.json --severity high
          python scripts/provenance_v4.py
          python scripts/threshold_sign.py
          python scripts/quorum_verify.py
          python scripts/rekor_api.py --file codex/manifest.v96.json
