name: codex-deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG_B64: ${{ secrets.KUBE_CONFIG }}
      NS: codex
      IMAGE: ghcr.io/${{ github.repository_owner }}/codex-v90x:latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        run: |
          echo "$KUBECONFIG_B64" | base64 -d > $HOME/kubeconfig
          echo "KUBECONFIG=$HOME/kubeconfig" >> $GITHUB_ENV

      - name: Create namespace if missing
        run: |
          kubectl get ns $NS || kubectl create ns $NS

      - name: Create/Update secret with API key
        env:
          CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
        run: |
          kubectl -n $NS create secret generic codex-secrets \
            --from-literal=CODEX_API_KEY="$CODEX_API_KEY" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy via Helm (pin image tag)
        run: |
          helm upgrade --install codex k8s/helm -n $NS \
            --set image.repository="ghcr.io/${{ github.repository_owner }}/codex-v90x" \
            --set image.tag="latest" \
            --set service.port=80

      - name: Wait for rollout
        run: kubectl -n $NS rollout status deploy/codex-v89-aeon --timeout=120s || true
